import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import Header from "./components/header";
import NextProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  `}>
        <NextProvider>
          <div className="flex relative h-screen overflow-hidden w-screen">
            <Nav />
            <div className="max-h-screen overflow-hidden"> {children}</div>{" "}
          </div>
        </NextProvider>
      </body>
    </html>
  );
}
