import React from "react";
const columns = [
  { name: "NAME", uid: "name", sortable: true },
  { name: "DATE", uid: "date", sortable: true },
  { name: "AMOUNT", uid: "amount" },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "INVOICE", uid: "invoice", sortable: true },
];

const statusOptions = [
  { name: "Paid", uid: "paid" },
  { name: "Refund", uid: "refund" },
];

const users = [
  {
    amount: "$ 80,000",
    id: 1,
    name: "Tony Reichert",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    amount: "$80,000",
    id: 2,
    name: "Zoey Lang",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    amount: "$ 80,000",
    id: 3,
    name: "Jane Fisher",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    amount: "$ 80,000",
    id: 4,
    name: "William Howard",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    amount: "$ 80,000",
    id: 5,
    name: "Kristen Copper",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    amount: "$ 80,000",
    id: 6,
    name: "Brian Kim",
    age: 32,
    date: "Nov. 15, 2023",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "paid",
  },
  {
    amount: "$ 80,000",
    id: 7,
    name: "Michael Hunt",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    amount: "$ 80,000",
    id: 8,
    name: "Samantha Brooks",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    amount: "$ 80,000",
    id: 9,
    name: "Frank Harrison",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    amount: "$ 80,000",
    id: 10,
    name: "Emma Adams",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    amount: "$ 80,000",
    id: 11,
    name: "Brandon Stevens",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    amount: "$ 80,000",
    id: 12,
    name: "Megan Richards",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    amount: "$ 80,000",
    id: 13,
    name: "Oliver Scott",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    amount: "$ 80,000",
    id: 14,
    name: "Grace Allen",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    amount: "$ 80,000",
    id: 15,
    name: "Noah Carter",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    amount: "$ 80,000",
    id: 16,
    name: "Ava Perez",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    amount: "$ 80,000",
    id: 17,
    name: "Liam Johnson",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    amount: "$ 80,000",
    id: 18,
    name: "Sophia Taylor",
    age: 32,
    date: "Testing",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    amount: "$ 80,000",
    id: 19,
    name: "Lucas Harris",
    age: 32,
    date: "Nov. 15, 2023",
    status: "refund",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    amount: "$ 80,000",
    id: 20,
    name: "Mia Robinson",
    age: 32,
    date: "Nov. 15, 2023",
    status: "paid",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export { columns, users, statusOptions };
